# Set hostname present in the Kerberos Realm and /etc/hosts 127.0.0.1
# Keytab is optional
# app:
#    keytab-location: /tmp/keytab.keytab
app:
    user-principal: CLI/clientuser.domain.com@DOMAIN.COM
    access-url: http://service.domain.com:8081/hello
    use-http-client: true